https://github.com/bradarm/dapr_offline_install

# Dapr Offline Installer
# A standalone dapr installation for offline, air-gapped, or disconnected use-cases.

# Usage
# The basic flow for using this package is as follows:

# Pre-stage all dapr artifacts necessary for offline installation via prestage.sh
# Deploy the prestaged directory generated by prestage.sh and install.sh to the desired host
# Install dapr via install.sh

# Pre-Staging
/home/thierry/dapr_offline_install
bash prestage.sh -a amd64 -v 1.5.1
dir ./prestaged

# Directory: /home/thierry/dapr_offline_install/prestaged

    # UnixMode   User             Group                 LastWriteTime           Size Name
    # --------   ----             -----                 -------------           ---- ----
    # drwxr-xr-x root             root               31/12/2021 16:57             48 components
    # -rw-r--r-- root             root               31/12/2021 16:57            187 config.yaml
    # -rw-r--r-- root             root               31/12/2021 16:57       23589233 dapr_linux_amd64.tar.gz
    # -rw------- root             root               31/12/2021 16:57      215791616 dapr_placement.tar
    # -rw-r--r-- root             root               31/12/2021 16:58       27601922 daprd_linux_amd64.tar.gz
    # -rw------- root             root               31/12/2021 16:57      116304384 redis.tar
    # -rw------- root             root               31/12/2021 16:57      155832832 zipkin.tar

# Installation
docker images
docker rmi 4f3481bffb17 8902b27a494d 2e167fbb9ce6 7614ae9453d1 --force

cd /home/thierry/dapr_offline_install
bash install.sh


docker images
    # REPOSITORY          TAG       IMAGE ID       CREATED       SIZE
    # k8s.gcr.io/etcd     latest    971a61e50664   4 hours ago   255MB
    # redis               latest    7614ae9453d1   9 days ago    113MB
    # openzipkin/zipkin   latest    0614d392dbc2   11 days ago   155MB
    # daprio/dapr         1.5.1     226aa2a3ceeb   3 weeks ago   214MB

dir /root/.dapr






